<?php
require_once('tools/config.php');
require_once('tools/functions.php');
checkActualPage(@$_GET['page']);
include_once('blocks/head.php');
include_once('blocks/header.php');
showActualPage();
include_once('blocks/footer.php');
include_once('blocks/foot.php');
?>