<?php
require_once('tools/config.php');
require_once('tools/functions.php');
checkActualPage(@$_GET['page']);
getBlock('head');
getBlock('header');
showActualPage();
getBlock('footer');
getBlock('foot');
?>